# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resources\ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_xmin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_xmin.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_xmin.setObjectName("lineEdit_xmin")
        self.gridLayout.addWidget(self.lineEdit_xmin, 1, 0, 1, 1)
        self.lineEdit_xdpi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_xdpi.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_xdpi.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_xdpi.setObjectName("lineEdit_xdpi")
        self.gridLayout.addWidget(self.lineEdit_xdpi, 1, 2, 1, 1)
        self.widget_plot = PlotWidget(self.centralwidget)
        self.widget_plot.setMinimumSize(QtCore.QSize(0, 300))
        self.widget_plot.setObjectName("widget_plot")
        self.gridLayout.addWidget(self.widget_plot, 0, 0, 1, 3)
        self.lineEdit_xmax = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_xmax.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_xmax.setObjectName("lineEdit_xmax")
        self.gridLayout.addWidget(self.lineEdit_xmax, 1, 1, 1, 1)
        self.pushButton_buildPlot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_buildPlot.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_buildPlot.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_buildPlot.setObjectName("pushButton_buildPlot")
        self.gridLayout.addWidget(self.pushButton_buildPlot, 2, 2, 1, 1)
        self.lineEdit_formula = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_formula.setObjectName("lineEdit_formula")
        self.gridLayout.addWidget(self.lineEdit_formula, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit_xmin.setText(_translate("MainWindow", "0"))
        self.lineEdit_xmin.setPlaceholderText(_translate("MainWindow", "x min"))
        self.lineEdit_xdpi.setText(_translate("MainWindow", "0.1"))
        self.lineEdit_xdpi.setPlaceholderText(_translate("MainWindow", "x dpi"))
        self.lineEdit_xmax.setText(_translate("MainWindow", "5"))
        self.lineEdit_xmax.setPlaceholderText(_translate("MainWindow", "x max"))
        self.pushButton_buildPlot.setText(_translate("MainWindow", "build"))
        self.lineEdit_formula.setText(_translate("MainWindow", "sin(x)"))
        self.lineEdit_formula.setPlaceholderText(_translate("MainWindow", "f(x)"))
from .plotwidget import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
